platform :ios, '16.1'

target 'Meedly' do
  
  use_frameworks!

  pod 'Kingfisher', '~> 7.4'
	pod 'Swinject', '~> 2.8'
	pod 'Alamofire', '~> 5.6'
	pod 'FeedKit', '~> 9.1'
  pod 'SnapKit', '~> 5.6'
  pod 'Then', '~> 3.0'

end
