# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Meedly' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'PINRemoteImage', '~> 3.0'
	pod 'Swinject', '~> 2.8'
	pod 'Alamofire', '~> 5.6'
	pod 'FeedKit', '~> 9.1'

end
